<a href="https://colab.research.google.com/github/MohsinAzad32/Linear-Regression/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/Machine Learning

/content/drive/MyDrive/Machine Learning


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
data = {
    "Age": [
        22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50, 51
    ],
    "Salary": [
        28000, 30000, 32000, 35000, 37000, 39000, 42000, 44000, 50000, 52000,
        54000, 56000, 58000, 60000, 63000, 65000, 67000, 69000, 72000, 74000,
        76000, 78000, 80000, 82000, 85000, 87000, 89000, 91000, 94000, 96000
    ]
}

df=pd.DataFrame(data)
df.head()


Age  Salary
0   22   28000
1   23   30000
2   24   32000
3   25   35000
4   26   37000

In [50]:
X=df['Age'].values.reshape(-1,1)
ones=np.ones(len(X))
x_new=np.column_stack((ones,X))
x_new

array([[ 1., 22.],
       [ 1., 23.],
       [ 1., 24.],
       [ 1., 25.],
       [ 1., 26.],
       [ 1., 27.],
       [ 1., 28.],
       [ 1., 29.],
       [ 1., 30.],
       [ 1., 31.],
       [ 1., 32.],
       [ 1., 33.],
       [ 1., 34.],
       [ 1., 35.],
       [ 1., 36.],
       [ 1., 37.],
       [ 1., 38.],
       [ 1., 39.],
       [ 1., 40.],
       [ 1., 41.],
       [ 1., 42.],
       [ 1., 43.],
       [ 1., 44.],
       [ 1., 45.],
       [ 1., 46.],
       [ 1., 47.],
       [ 1., 48.],
       [ 1., 49.],
       [ 1., 50.],
       [ 1., 51.]])

In [59]:
y=df['Salary'].values.reshape(-1,1)
y

array([[28000],
       [30000],
       [32000],
       [35000],
       [37000],
       [39000],
       [42000],
       [44000],
       [50000],
       [52000],
       [54000],
       [56000],
       [58000],
       [60000],
       [63000],
       [65000],
       [67000],
       [69000],
       [72000],
       [74000],
       [76000],
       [78000],
       [80000],
       [82000],
       [85000],
       [87000],
       [89000],
       [91000],
       [94000],
       [96000]])

In [60]:
x_transpose=np.transpose(x_new)
x_transpose

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.],
       [22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34.,
        35., 36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
        48., 49., 50., 51.]])

In [61]:
x_new.shape

(30, 2)

In [62]:
x_transpose.shape

(2, 30)

In [64]:
first=np.matmul(x_transpose,x_new)
first
first_inverse=np.linalg.inv(first)
first_inverse

array([[ 6.26103077e-01, -1.62402670e-02],
       [-1.62402670e-02,  4.44938821e-04]])

In [65]:
second=np.matmul(np.matmul(first_inverse,x_transpose),y)
second

array([[-22907.15609937],
       [  2349.05450501]])

In [66]:
second[0]

array([-22907.15609937])

In [67]:
second[1]

array([2349.05450501])

Now we are implementing direct Linear Regression model on our dataset

In [70]:
df=pd.read_csv('salary_dataset.csv')
df.head()

Age  Salary
0   58   67205
1   48   56672
2   34   35269
3   27   26419
4   40   52062

In [83]:
X_train=df[['Age']]
X_train

Age
0    58
1    48
2    34
3    27
4    40
..  ...
95   47
96   26
97   28
98   27
99   31

[100 rows x 1 columns]

In [84]:
y=df['Salary']

In [73]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import  metrics

In [78]:
model=LinearRegression()

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X_train,y,test_size=0.2,random_state=42)

In [85]:
model.fit(X_train,y)

LinearRegression()

In [88]:
y_predic=model.predict(X_train)

In [90]:
print('intercept', model.intercept_)
print('weight',model.coef_[0])

intercept 488.09063110370334
weight 1185.9275646866024


In [94]:
mse=metrics.mean_squared_error(y,y_predic)
rmse=np.sqrt(mse)
r2=metrics.r2_score(y,y_predic)

In [95]:
print('Mean Squared Error: ',mse)
print('Root Mean Squared Error: ',rmse)
print('R2 Score: ',r2)

Mean Squared Error:  22061242.936093375
Root Mean Squared Error:  4696.939741586363
R2 Score:  0.8975453901536397
